# Generated by Django 4.1.2 on 2022-12-24 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment_reply_alter_comment_is_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='is_reply',
            new_name='is_replay',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AddField(
            model_name='comment',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rcomment', to='home.comment'),
        ),
    ]
